# -*- coding: utf-8 -*-
"""RF-IEEE_CIS_Fraud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTdiRhcIgHcajc5YGQhyrSn1ZOdXGy6m
"""

import pandas
import numpy
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.metrics import (
    log_loss,
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    precision_recall_curve,
    roc_curve
)
from sklearn.ensemble import RandomForestClassifier
from typing import Dict, List, Tuple


# Importing the files
train = pandas.read_csv(r'.............')
validation = pandas.read_csv(r'.............')
test = pandas.read_csv(r'.............')

print(len(train) + len(validation) + len(test))

"""# Node Column Handling"""
# - These node columns are used to specifically consider the GNNs requirements for the nodes. 

# Identify categorical columns
categorical_cols = train.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print(f"Categorical columns identified for encoding: {categorical_cols}")

encoders = {}

for col in categorical_cols:

    # Ensure string type for safety
    train[col] = train[col].astype(str)
    validation[col] = validation[col].astype(str)
    test[col] = test[col].astype(str)

    # Fit ONLY on train
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])

    encoders[col] = le

    # Create mapping dictionary for safe transform
    mapping = {cls: idx for idx, cls in enumerate(le.classes_)}

    # Apply safe mapping to validation and test
    validation[col] = validation[col].map(mapping).fillna(-1).astype(int)
    test[col] = test[col].map(mapping).fillna(-1).astype(int)


""" Function for training the model """
def train_evaluate_random_forest(
    train_df,
    val_df,
    test_df,
    target_col='isFraud',
    *,
    n_estimators: int = 200,
    max_depth: int | None = None,
    min_samples_leaf: int = 5,
    class_weight: str | dict = "balanced",
    random_state: int = 42,
    paper_mode: bool = False,          # NEW
    return_test_probs: bool = False    # NEW
):

    
    # Prepare X and y
    X_train = train_df.drop(columns=[target_col])
    y_train = train_df[target_col]

    X_val = val_df.drop(columns=[target_col])
    y_val = val_df[target_col]

    X_test = test_df.drop(columns=[target_col])
    y_test = test_df[target_col]
    
    # 1. Model
    
    rf = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
        n_jobs=1,
        class_weight=class_weight,
        random_state=random_state,
    )

    # 2. Fit
    
    rf.fit(X_train, y_train)

    # 3. Probability predictions
    
    train_probs = rf.predict_proba(X_train)[:, 1]
    val_probs   = rf.predict_proba(X_val)[:, 1]
    test_probs  = rf.predict_proba(X_test)[:, 1]


    # 4. Paper-style metrics (threshold-free)
    train_metrics = {
        "roc_auc": roc_auc_score(y_train, train_probs),
        "pr_auc": average_precision_score(y_train, train_probs),
    }

    val_metrics = {
        "roc_auc": roc_auc_score(y_val, val_probs),
        "pr_auc": average_precision_score(y_val, val_probs),
    }

    test_metrics = {
        "roc_auc": roc_auc_score(y_test, test_probs),
        "pr_auc": average_precision_score(y_test, test_probs),
    }

    # 5. Deployment-style metrics (optional)
    best_t = None
    test_preds = None # Initialize test_preds

    if not paper_mode:
        thresholds = numpy.linspace(0.01, 0.5, 100)
        best_t, best_f1 = 0.5, 0.0

        for t in thresholds:
            preds = (val_probs >= t).astype(int)
            f1 = f1_score(y_val, preds, zero_division=0)
            if f1 > best_f1:
                best_f1 = f1
                best_t = t

        test_preds = (test_probs >= best_t).astype(int)

        tn, fp, fn, tp = confusion_matrix(y_test, test_preds).ravel()

        test_metrics.update({
            "accuracy": accuracy_score(y_test, test_preds),
            "precision": precision_score(y_test, test_preds, zero_division=0),
            "recall": recall_score(y_test, test_preds, zero_division=0),
            "f1": f1_score(y_test, test_preds, zero_division=0),
            "specificity": tn / (tn + fp) if (tn + fp) > 0 else 0.0,
        })

    # 6. Return
    
    out = {
        "model": rf,
        "train_metrics": train_metrics,
        "val_metrics": val_metrics,
        "test_metrics": test_metrics,
        "best_threshold": best_t,
    }

    if return_test_probs:
        out["test_probs"] = test_probs
        out["y_test"] = y_test.values

    # Add actual and predicted values dataframe
    if test_preds is not None:
        out['predictions_df'] = pandas.DataFrame({
            'randomforest_actual': y_test.values,
            'randomforest_predicted': test_preds,
            'randomforest_probs': test_probs
        })

    return out


""" Function """
def run_model_with_seeds_collect(
    train,
    validation,
    test,
    *,
    trainer_fn,
    seeds=[27],
    target_col="isFraud",
    verbose=True,
):

    def _extract_y_and_probs(res: dict):
        # Prefer explicit arrays if available
        if "test_probs" in res and "y_test" in res:
            y = np.asarray(res["y_test"]).astype(int).ravel()
            p = np.asarray(res["test_probs"]).astype(float).ravel()
            return y, p

        # Otherwise use predictions_df
        if "predictions_df" not in res:
            raise KeyError("Expected res to include ('test_probs','y_test') or 'predictions_df'.")

        df = res["predictions_df"]
        if target_col not in df.columns:
            raise KeyError(f"predictions_df missing target_col='{target_col}'.")

        # Heuristic: pick a prob/pred column
        prob_candidates = [c for c in df.columns if c != target_col and ("prob" in c.lower() or "pred" in c.lower())]
        if prob_candidates:
            prob_col = prob_candidates[0]
        else:
            numeric_cols = [c for c in df.columns if c != target_col and pd.api.types.is_numeric_dtype(df[c])]
            if not numeric_cols:
                raise KeyError("Could not find a probability column in predictions_df.")
            prob_col = numeric_cols[0]

        y = df[target_col].to_numpy(dtype=int).ravel()
        p = df[prob_col].to_numpy(dtype=float).ravel()
        return y, p

    all_metrics_rows = []
    pr_auc_rows = []
    probs_list = []
    y_ref = None

    for seed in seeds:
        if verbose:
            print(f"\n====== Running model with seed {seed} ======")

        res = trainer_fn(seed)

        # ---- metrics dict (whatever your trainer returns) ----
        metrics = res.get("test_metrics", {})
        trainmetrics = res.get("train_metrics", {})
        valmetrics = res.get("val_metrics", {})
        if verbose:
            print("test_metrics:", metrics)

        # ---- extract y/probs and compute PR-AUC consistently ----
        y_true, probs = _extract_y_and_probs(res)

        if y_ref is None:
            y_ref = y_true
        else:
            # ensure exact same test order across seeds
            if len(y_true) != len(y_ref) or not np.array_equal(y_true, y_ref):
                raise ValueError(
                    "y_true mismatch across seeds. Ensure the SAME test set order is used every run."
                )

        # PR-AUC (Average Precision)
        pr_auc = average_precision_score(y_true, probs)

        # store all metrics + computed pr_auc + seed
        row = {"seed": seed, **metrics, "pr_auc": pr_auc}
        all_metrics_rows.append(row)

        pr_auc_rows.append({"seed": seed, "pr_auc": pr_auc})
        probs_list.append(probs)

    
    # DataFrames

    metrics_df = pd.DataFrame(all_metrics_rows)
    pr_auc_df = pd.DataFrame(pr_auc_rows)

    # averaged metrics (numeric only)
    avg_metrics = metrics_df.drop(columns=["seed"], errors="ignore").mean(numeric_only=True).to_dict()

    # averaged probs dataframe with actuals
    probs_mat = np.vstack(probs_list)  # (n_seeds, n_samples)
    avg_prob = probs_mat.mean(axis=0)

    avg_probs_df = pd.DataFrame({
        target_col: y_ref,
        "avg_prob": avg_prob
    })

    return avg_metrics, pr_auc_df, avg_probs_df, metrics_df

def rf_trainer(seed):
    return train_evaluate_random_forest(
        train,
        validation,
        test,
        target_col="isFraud",
        paper_mode=False,
        return_test_probs=True,
        n_estimators=500,
        max_depth=20,
        random_state=seed,
    )

avg_metrics, pr_auc_df, avg_probs_df, metrics_df = run_model_with_seeds_collect(
    train, validation, test,
    trainer_fn=rf_trainer,
    target_col="isFraud",
    verbose=True
)


""" Metric Saves """
pr_auc_df.to_csv('/content/drive/MyDrive/Dataset/predictedones/randomfores/prauc.csv')
avg_probs_df.to_csv('/content/drive/MyDrive/Dataset/predictedones/randomfores/avgProbs.csv')


